name: Scheduled Health Check

# Controls when the action will run.
on:
  schedule:
    - cron: "*/2 * * * *"

env:
  SLACK_WEBHOOK_URL: "{{ secrets.SLACK_WEBHOOK_URL }}"

permissions: read-all|write-all

jobs:
  health_check_job_sandbox:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh sandbox
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
